# Start coordinates [x, y] or generate_random
start_pose: [0.0, 0.0]

# Goal coordinates [x, y] or generate_random
goal_pose: [100.0, 100.0]

# Obstacles
obstacles:
  - type  : Line
    start : [-10, 10]
    end   : [10, 10]
  - type  : Line
    start : [-10, 10]
    end   : [-10, -10]
  - type  : Line
    start : [10, 10]
    end   : [10, -10]
  - type  : Circle
    center: [50, 50]
    radius: 5

# Search space grid
grid:
  xlimits: [-100.0, 100.0]
  ylimits: [-100.0, 100.0]
  spacing: [1.0, 1.0]

# RRT
rrt:
  max_step_size           : 50.0
  min_iterations          : 100
  max_iterations          : 10000
  goal_closeness_threshold: 3.0
